project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - syllabus.qmd
      - about.qmd 

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

